service: discord-wordle

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-1

functions:
  default:
    handler: src/handler.default
    memorySize: 128
    events:
      - schedule: cron(0 11 * * ? *)
    environment:
      DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}
