frameworkVersion: "3"

service: discord-wordle

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  default:
    handler: src/handler.default
    memorySize: 128
    events:
      - schedule: cron(0 11 * * ? *)
    environment:
      DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}

custom:
  esbuild:
    target: node16
